
# List of sources, grouped by source type
# No 2 sources may have the same name, even if their types are different
sources:
    webhook test source:
        test_source1:
            description: Test source that utilises webhooks
    on demand test source:
        test_source2:
            description: Test source that works on-demand
            minimal_refresh_delay: 5

feeds:
    test_feed:
        description: Some test feed
        sources:
            - test_source1
            - test_source2
users:
    test_user:
        description: Test user
        feeds:
            - test_feed
            
